### ISSUE TITLE
supprime.

### ISSUE THREAD

**Issue by KSCHdsc** [Inplex-sys/BlackCap-Grabber-NoDualHook#1]
diffamation

**Comment by Anatik572** [comment]
Bah si je viens de voir il y a bien a dual hook merci @Inplex-sys ! 
(ps : arrête de pleurer clinche)

**Comment by furax124** [comment]
> Bah si je viens de voir il y a bien a dual hook merci @Inplex-sys !
> (ps : arrête de pleurer clinche)

Preuve ?

**Comment by KSCHdsc** [comment]
Regarde les autres issues qu’il a close… tous le monde dit le contraire il veut simplement me faire de la concurrence…

**Comment by KSCHdsc** [comment]
Écoute même pas les gens comme ça

**Comment by Inplex-sys** [comment]
[Preuve ICI](https://github.com/Inplex-sys/BlackCap-Grabber-NoDualHook/blob/main/proof.md)

**Comment by KSCHdsc** [comment]
Il est dit sur mon github que cet url sert au futur web panel via glitch.com c’est ÉCRIT

**Comment by Inplex-sys** [comment]
Dans quel but tu envoies une copie des donnés collectées ?
Tu viens me donner l'idée de mettre dans le README

**Comment by KSCHdsc** [comment]
C’est pour des test effectué via mes panel à moi les données des autres ne sont pas collecte c’est pour une future mise à jour

**Comment by KSCHdsc** [comment]
Il n’y a que les données issue de mon ordinateur qui sont collecté sur cette api elle n’est pas active sur le project github si les gens ont envie de ne pas l’utiliser libre a eu de reprendre l’injection et d’enlever le lien glitch c’est pour ça que j’ai ajouté le lien de l’injection dans la config

**Comment by Inplex-sys** [comment]
Bah pourquoi les envoyées donc et le serveur réponds une réponse `HTTP 200 OK` ce qui signifie que il y a une réponse
et un traitement des données côté serveur

**Comment by KSCHdsc** [comment]
Oui mais banalisé

**Comment by Inplex-sys** [comment]
C'est a dire ?

**Comment by KSCHdsc** [comment]
Il y a un filtre au niveau du desktop name mis à part si tu as le même nom d’ordinateur que moi (j’en doute) la donnée est banalisé

**Comment by KSCHdsc** [comment]
Et non récolté par mon api

**Comment by KSCHdsc** [comment]
Enfin bon si tu avais lu quelques lignes que j’ai écrite dans tes mp Discord tu le comprendrais et tu supprimerais ce repo vulgairement diffamatoire

**Comment by Inplex-sys** [comment]
L'envoie de données confidentiel sur un site web qu'il soit traité ou non enfreint la lois

**Comment by Inplex-sys** [comment]
Il y a rien a comprendre, tu réfutes juste en avançant des preuves qui n'en sont pas, c'est simple je mettrais les preuves
dans le README et libre aux gens de tranché

**Comment by KSCHdsc** [comment]
Dans ce cas là l’utilisation d’api de transmission de request est illégal, oh shit gg tu m’as eu.
Les database de login en ligne aussi? Ptn t’es trop fort!

**Comment by KSCHdsc** [comment]
Dans ce cas là enlève « dual hook » de ton title vue que tu NE SAIS PAS comment la donnée est utilisé et traité.

**Comment by KSCHdsc** [comment]
Je ne prendrais pas le temps de me défendre si je faisais réellement du dualhook

**Comment by Inplex-sys** [comment]
Non car c'est des informations qui sont relatif au fonctionnement du site en question, alors que un token de sessions
discord n'est utile que dans des fins malveillantes

**Comment by Inplex-sys** [comment]
Bah si au contraire

**Comment by KSCHdsc** [comment]
Ah bon donc les logins via oauth sont tous malveillant mince alors! Il faut report discordbot

**Comment by KSCHdsc** [comment]
Et tu close l’issue car tu n’as plus d’argument

**Comment by KSCHdsc** [comment]
Bravo ça montre ta supériorité intellectuelle! T’es vraiment un génie

**Comment by Inplex-sys** [comment]
Dit-il

**Comment by Inplex-sys** [comment]
Tes arguments "Oui je vole les données mais je les utilises pas" 🤡

**Comment by KSCHdsc** [comment]
Close les issues ne te mènera nul par.. comme la création de ce repo.
Je t’aurais limite proposer de work avec moi comme la plupart des dev avec qui je discute mais vue que t’es jaloux maladif de mon projet je trouve ça vraiment gênant

**Comment by KSCHdsc** [comment]
Mon argument c’est:
Tu ne sais ni comment on utilise les données ni comment les données sont « stocké » et tu parles de dualhook pour te rendre intéressant

**Comment by KSCHdsc** [comment]
Mais j’ai une question à te poser.
Si il y avait vraiment un dualhook.
Pourquoi personne ne se plaint ?

**Comment by KSCHdsc** [comment]
C’est ma dernière question je te laisse y répondre et ensuite je n’écrirais plus sous ce repo ridicule

**Comment by Inplex-sys** [comment]
Tu vas finir par croire a tes propres mensonges et puis je n'est rien a envier a toi

**Comment by Inplex-sys** [comment]
Car les gens ne regarde pas et les gens qui sont intéresser ne regarde pas en profondeur
