### ISSUE TITLE
I'm getting an error when I test the compiled .exe

### ISSUE THREAD

**Issue by xdtadas123** [Inplex-sys/BlackCap-Grabber-NoDualHook#19]
Traceback (most recent call last):
  File "obfuscated_name.py", line 1, in <module>
ImportError: DLL load failed while importing win32gui: The specified module could not be found.

**Comment by Inplex-sys** [comment]
pip install pywin32

**Comment by xdtadas123** [comment]
I had it, after reinstall it still gives the same error.

**Comment by Inplex-sys** [comment]
https://github.com/mhammond/pywin32/issues/1730
