### ISSUE TITLE
is it a virus ?

### ISSUE THREAD

**Issue by PetLuck** [Inplex-sys/BlackCap-Grabber-NoDualHook#26]
If you do not believe me, look how he installs the package "advancedrequests" on your system. you can look at the code and see another package called "rangenlib" which is the RAT. the code does the following:
steal your minecraft ssids
steal your discord tokens
once you copy a crypto address, it will replace the address in your clipboard with another one that is his.
the full list is here:
https://github.com/Inplex-sys/BlackCap-Grabber-NoDualHook

**Comment by Inplex-sys** [comment]
Where are the `advancedrequests` and `rangenlib` packages mentioned in the repos ?
